# Generated by Django 3.2.9 on 2021-11-05 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20211105_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='amount_of_up_votes',
            new_name='votes',
        ),
    ]
