# Generated by Django 3.2.9 on 2021-11-06 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0004_rename_amount_of_up_votes_news_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='votes',
        ),
        migrations.AddField(
            model_name='news',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='backend.news'),
        ),
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
