version: "3.7"
services:
  news_db:
    image: postgres:10-alpine
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432-5432"

  news_backend:
    build: ./backend/
    command : bash -c "
      python ./backend/manage.py makemigrations &&
      python ./backend/manage.py migrate &&
      python ./backend/manage.py runserver 0.0.0.0:8000"
    volumes:
    - .:/usr/src/backend
    ports:
      - "8000:8000"
    depends_on:
      - news_db

  news_frontend:
    build: ./frontend/
    command : ["npm", "start", "--prefix client"]
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - news_backend
