# Generated by Django 3.2.9 on 2021-11-05 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=400)),
                ('amount_of_up_votes', models.IntegerField(default=0)),
                ('author_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('author_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.user')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.news')),
            ],
        ),
    ]
