# Generated by Django 3.2.9 on 2021-11-06 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0007_alter_news_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='liked_by',
        ),
        migrations.AddField(
            model_name='news',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='voted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
