# Generated by Django 3.2.9 on 2021-11-06 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20211106_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservotes',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
