# Generated by Django 3.2.9 on 2021-11-06 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_uservotes_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserVotes',
        ),
    ]
