# Generated by Django 3.2.9 on 2021-11-07 09:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0012_votenews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votenews',
            old_name='user',
            new_name='author_name',
        ),
        migrations.AlterUniqueTogether(
            name='votenews',
            unique_together={('author_name', 'news')},
        ),
    ]
