# Generated by Django 3.2.9 on 2021-11-07 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20211107_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votenews',
            name='total_votes',
        ),
    ]
